### ISSUE TITLE
Which framework do you plan to use fo this website?

### ISSUE THREAD

**Issue by Jak2k** [binwiederhier/ntfy-blog.github.io#1]

**Comment by binwiederhier** [comment]
Haha. That was quick. I'll use mkdocs with the mkdocs-material theme, just like I did for the ntfy docs.

**Comment by Jak2k** [comment]
mkdocs is for docs not for blogs?

I created [my blog](https://jak2k.schwanenberg.name/) with [astro](https://astro.build/) and can really recommend it.

**Comment by binwiederhier** [comment]
I'm glad that that worked for you. I'll use mkdocs with the blog plugin. It works wonderfully.
